#!/usr/bin/env python3
"""Embed src/prelude/prelude.js as a C string table (src/prelude/prelude.h).

The prelude is the engine-bundled pure-JS layer (F3 math helpers and
procedural primitives). It ships to both bindings: the desktop runtime
evaluates the embedded string at init; the web bridge exports the same
string to entry.js (ADR 0022 — one source, identical semantics).

Regenerate after editing prelude.js and commit both files:
    python3 tools/gen_prelude.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "prelude" / "prelude.js"
OUT = ROOT / "src" / "prelude" / "prelude.h"

data = SRC.read_bytes()

lines = []
lines.append("/* GENERATED by tools/gen_prelude.py from src/prelude/prelude.js")
lines.append(" * — edit the .js source and regenerate; do not edit by hand.")
lines.append(" */")
lines.append("#ifndef EFX_PRELUDE_H")
lines.append("#define EFX_PRELUDE_H")
lines.append("")
lines.append("static const char EFX_JS_PRELUDE[] = {")
for i in range(0, len(data), 16):
    chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
    lines.append("    " + chunk + ",")
lines.append("    0};")
lines.append("")
lines.append("static const unsigned EFX_JS_PRELUDE_LEN = %d;" % len(data))
lines.append("")
lines.append("#endif")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(data)} bytes of prelude)")
