/*
 * Sokol implementation of the render-module GPU sink: canned 2D quad
 * shader + 3D mesh shader (sokol-shdc generated, ADR 0015/0021), blend
 * pipeline variants, dynamic quad batching and indexed mesh playback
 * with depth (design D1–D7, F3).
 */
#include "platform/pipeline.h"
#include "platform/backend.h"
#include "render/render.h"
#include "math/efx_math.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "sokol_gfx.h"

/* interleaved quad vertex: pos(2f) uv(2f) color(ub4n) = 20 bytes */
typedef struct {
    float x, y, u, v;
    uint8_t r, g, b, a;
} pipe_vertex;

/* interleaved mesh vertex: pos(3f) color(4f) = 28 bytes — the F3 canned
 * shader consumes only position and color; normals/uvs stay in MeshData
 * storage and join the GPU layout in F4 (design D1, amended) */
typedef struct {
    float x, y, z;
    float r, g, b, a;
} pipe_mesh_vertex;

typedef struct {
    sg_image img;
    sg_view view;
} pipe_tex;

typedef struct {
    sg_buffer vbuf, ibuf;
    int index_count; /* 0 = non-indexed (draw vertex count) */
    int vertex_count;
} pipe_mesh_surface;

typedef struct {
    int surface_count;
    pipe_mesh_surface *surfaces;
} pipe_mesh;

typedef struct {
    sg_shader quad_shd;
    sg_pipeline quad_pip[3];
    sg_shader mesh_shd;
    sg_pipeline mesh_pip[3];
    sg_sampler smp;
    sg_buffer vbuf;
    pipe_vertex *scratch;
    int scratch_cap;
    int installed;
    int depth_remap; /* D3D11/Metal: fold 0..1 depth range into MVP */
    /* TEMPORARY F3 diagnostics (removed after the gate is green) */
    int diag_nocull;
    int diag_noremap;
    int diag_nodepth;
    int diag_noib;
    int diag_constz;
    int diag_posonly;
    int diag_u16;
    int diag_hardcube;
} pipe_state;

static pipe_state P;

/* TEMPORARY F3 diagnostics */
static int diag_env(const char *k) {
    const char *v = getenv(k);
    return v && *v && *v != '0';
}
static int DIAG_NOIB, DIAG_CONSTZ, DIAG_POSONLY, DIAG_U16, DIAG_HARDCUBE;

#define SOKOL_SHDC_IMPL
#include "shaders/quad.h" /* generated by sokol-shdc from shaders/quad.glsl (ADR 0021) */
#include "shaders/mesh.h" /* generated by sokol-shdc from shaders/mesh.glsl (ADR 0021) */

static void *pipe_create_texture(void *ud, int w, int h, const uint8_t *rgba) {
    (void)ud;
    pipe_tex *t = calloc(1, sizeof(pipe_tex));
    t->img = sg_make_image(&(sg_image_desc){
        .width = w,
        .height = h,
        .pixel_format = SG_PIXELFORMAT_RGBA8,
        .data = {.mip_levels[0] = {.ptr = rgba, .size = (size_t)w * h * 4}},
    });
    t->view = sg_make_view(&(sg_view_desc){
        .texture.image = t->img,
    });
    return t;
}

static void pipe_destroy_texture(void *ud, void *native) {
    (void)ud;
    pipe_tex *t = (pipe_tex *)native;
    if (t) {
        sg_destroy_view(t->view);
        sg_destroy_image(t->img);
        free(t);
    }
}

static void *pipe_create_mesh(void *ud, const efx_mesh_gpu_surface *surfs,
                              int count) {
    (void)ud;
    if (count < 1) {
        return NULL;
    }
    pipe_mesh *m = calloc(1, sizeof(pipe_mesh));
    if (!m) {
        return NULL;
    }
    m->surface_count = count;
    m->surfaces = calloc((size_t)count, sizeof(pipe_mesh_surface));
    if (!m->surfaces) {
        free(m);
        return NULL;
    }
    for (int i = 0; i < count; i++) {
        pipe_mesh_surface *d = &m->surfaces[i];
        d->vertex_count = surfs[i].vertex_count;
        d->index_count = surfs[i].index_count;
        if (DIAG_POSONLY) {
            /* positions-only stride-12 copy of the same vertices */
            float *pos = malloc((size_t)surfs[i].vertex_count * 12);
            for (int v = 0; v < surfs[i].vertex_count; v++) {
                pos[v * 3] = surfs[i].interleaved[v * 12];
                pos[v * 3 + 1] = surfs[i].interleaved[v * 12 + 1];
                pos[v * 3 + 2] = surfs[i].interleaved[v * 12 + 2];
            }
            d->vbuf = sg_make_buffer(&(sg_buffer_desc){
                .data = {.ptr = pos,
                         .size = (size_t)surfs[i].vertex_count * 12}});
            free(pos);
        } else {
            d->vbuf = sg_make_buffer(&(sg_buffer_desc){
                .data = {.ptr = surfs[i].interleaved,
                         .size = (size_t)surfs[i].vertex_count *
                                 sizeof(pipe_mesh_vertex)},
            });
        }
        if (surfs[i].indices) {
            if (DIAG_U16) {
                uint16_t *u16 = malloc((size_t)surfs[i].index_count * 2);
                for (int k = 0; k < surfs[i].index_count; k++) {
                    u16[k] = (uint16_t)surfs[i].indices[k];
                }
                d->ibuf = sg_make_buffer(&(sg_buffer_desc){
                    .usage = {.index_buffer = true},
                    .data = {.ptr = u16,
                             .size = (size_t)surfs[i].index_count * 2}});
                free(u16);
            } else {
                d->ibuf = sg_make_buffer(&(sg_buffer_desc){
                    .usage = {.index_buffer = true},
                    .data = {.ptr = surfs[i].indices,
                             .size = (size_t)surfs[i].index_count *
                                     sizeof(uint32_t)},
                });
            }
        }
    }
    return m;
}

static void pipe_destroy_mesh(void *ud, void *native) {
    (void)ud;
    pipe_mesh *m = (pipe_mesh *)native;
    if (m) {
        for (int i = 0; i < m->surface_count; i++) {
            sg_destroy_buffer(m->surfaces[i].vbuf);
            sg_destroy_buffer(m->surfaces[i].ibuf);
        }
        free(m->surfaces);
        free(m);
    }
}

static uint32_t pack_color(const float c[4]) {
    uint32_t r = (uint32_t)(c[0] * 255.0f + 0.5f);
    uint32_t g = (uint32_t)(c[1] * 255.0f + 0.5f);
    uint32_t b = (uint32_t)(c[2] * 255.0f + 0.5f);
    uint32_t a = (uint32_t)(c[3] * 255.0f + 0.5f);
    return (a << 24) | (b << 16) | (g << 8) | r;
}

static pipe_vertex emit_vert(const efx_quad_record *r, int i) {
    /* corner i in strip order: TL, TR, BL, BR; local space is 0..w, 0..h */
    static const float lu[4] = {0, 1, 0, 1};
    static const float lv[4] = {0, 0, 1, 1};
    static const float su[4] = {0, 1, 0, 1};
    static const float sv[4] = {0, 0, 1, 1};
    pipe_vertex v;
    const uint32_t packed = pack_color(r->color);
    {
        float fx = r->m.a * lu[i] * r->w + r->m.c * lv[i] * r->h + r->m.tx;
        float fy = r->m.b * lu[i] * r->w + r->m.d * lv[i] * r->h + r->m.ty;
        v.x = 2.0f * fx / r->frame_w - 1.0f;
        v.y = 1.0f - 2.0f * fy / r->frame_h;
        v.u = (r->sx + su[i] * r->sw) / r->tw;
        v.v = (r->sy + sv[i] * r->sh) / r->th;
        v.r = (uint8_t)(packed & 0xff);
        v.g = (uint8_t)((packed >> 8) & 0xff);
        v.b = (uint8_t)((packed >> 16) & 0xff);
        v.a = (uint8_t)((packed >> 24) & 0xff);
    }
    return v;
}

static pipe_vertex *emit_quad(pipe_vertex *v, const efx_quad_record *r) {
    for (int i = 0; i < 4; i++) {
        *v++ = emit_vert(r, i);
    }
    return v;
}

static pipe_vertex *emit_quad_bridged(pipe_vertex *v, const efx_quad_record *r) {
    /* continue a strip: duplicate last vertex, then first vertex of the new
       quad twice, then the remaining three (two degenerate triangles) */
    v[0] = v[-1];
    v[1] = emit_vert(r, 0);
    v[2] = v[1];
    v += 3;
    for (int i = 1; i < 4; i++) {
        *v++ = emit_vert(r, i);
    }
    return v;
}


void efx_pipeline_install(void) {
    if (P.installed) {
        return;
    }
    memset(&P, 0, sizeof(P));

    /* TEMPORARY F3 diagnostics: read BEFORE pipeline creation so the
       pipeline-shape toggles take effect */
    P.diag_nocull = diag_env("EFX_DIAG_NOCULL");
    P.diag_noremap = diag_env("EFX_DIAG_NOREMAP");
    P.diag_nodepth = diag_env("EFX_DIAG_NODEPTH");
    DIAG_NOIB = diag_env("EFX_DIAG_NOIB");
    DIAG_CONSTZ = diag_env("EFX_DIAG_CONSTZ");
    DIAG_POSONLY = diag_env("EFX_DIAG_POSONLY");
    DIAG_U16 = diag_env("EFX_DIAG_U16");
    DIAG_HARDCUBE = diag_env("EFX_DIAG_HARDCUBE");
    fprintf(stderr,
            "DIAG: hardcube=%d nocull=%d noremap=%d nodepth=%d noib=%d "
            "posonly=%d u16=%d remap=%d\n",
            DIAG_HARDCUBE, P.diag_nocull, P.diag_noremap, P.diag_nodepth,
            DIAG_NOIB, DIAG_POSONLY, DIAG_U16, P.depth_remap);
    fflush(stderr);

    P.quad_shd = sg_make_shader(quad_shader_desc(sg_query_backend()));
    P.mesh_shd = sg_make_shader(mesh_shader_desc(sg_query_backend()));

    static const sg_blend_state blends[3] = {
        /* alpha: src*sa + dst*(1-sa) */
        {.enabled = true,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA},
        /* additive: dst + src*sa */
        {.enabled = true,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE},
        /* subtractive: dst - src*sa */
        {.enabled = true,
         .op_rgb = SG_BLENDOP_SUBTRACT,
         .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_rgb = SG_BLENDFACTOR_ONE,
         .op_alpha = SG_BLENDOP_SUBTRACT,
         .src_factor_alpha = SG_BLENDFACTOR_SRC_ALPHA,
         .dst_factor_alpha = SG_BLENDFACTOR_ONE},
    };

    for (int i = 0; i < 3; i++) {
        P.quad_pip[i] = sg_make_pipeline(&(sg_pipeline_desc){
            .shader = P.quad_shd,
            .primitive_type = SG_PRIMITIVETYPE_TRIANGLE_STRIP,
            .layout = {.buffers[0].stride = (int)sizeof(pipe_vertex),
                       .attrs = {[0] = {.format = SG_VERTEXFORMAT_FLOAT2},
                                 [1] = {.format = SG_VERTEXFORMAT_FLOAT2, .offset = 8},
                                 [2] = {.format = SG_VERTEXFORMAT_UBYTE4N, .offset = 16}}},
            .colors[0] = {.pixel_format = SG_PIXELFORMAT_RGBA8,
                          .blend = blends[i]},
            .depth = {.compare = SG_COMPAREFUNC_ALWAYS, .write_enabled = false},
            .cull_mode = SG_CULLMODE_NONE,
            .sample_count = 1,
        });
        /* mesh pipelines: indexed triangles, depth-tested and writing
           (design D4), backface culling on CCW front faces (design D6) */
        sg_pipeline_desc md = {
            .shader = P.mesh_shd,
            .primitive_type = SG_PRIMITIVETYPE_TRIANGLES,
            /* mesh surfaces always draw indexed; non-indexed surfaces get
               a synthesized identity index buffer at upload (render.c) */
            .index_type = DIAG_U16 ? SG_INDEXTYPE_UINT16
                                   : SG_INDEXTYPE_UINT32,
            /* Only the attributes the canned F3 shader consumes are
               declared: the HLSL/Metal compilers strip unused inputs from
               the shader signature, and a pipeline declaring them fails
               InputLayout/RPS creation on D3D11/Metal (GL is lenient).
               The 48-byte interleaved layout is unchanged; F4 re-adds
               attrs 1/2 when its shaders start reading normals/uvs. */
            .layout = DIAG_POSONLY
                ? (sg_vertex_layout_state){
                      .buffers[0].stride = 12,
                      .attrs = {[ATTR_mesh_a_pos] = {.format =
                                                     SG_VERTEXFORMAT_FLOAT3}}}
                : (sg_vertex_layout_state){
                      .buffers[0].stride = (int)sizeof(pipe_mesh_vertex),
                      .attrs = {[ATTR_mesh_a_pos] = {.format = SG_VERTEXFORMAT_FLOAT3, .offset = 0},
                                [ATTR_mesh_a_color] = {.format = SG_VERTEXFORMAT_FLOAT4, .offset = 12}}},
            /* slots 2 (normal) and 3 (uv) join in F4 when the canned
               shader starts consuming them */
            .colors[0] = {.pixel_format = SG_PIXELFORMAT_RGBA8,
                          .blend = blends[i]},
            .depth = {.compare = SG_COMPAREFUNC_LESS_EQUAL,
                      .write_enabled = true},
            .cull_mode = SG_CULLMODE_BACK,
            .face_winding = SG_FACEWINDING_CCW,
            .sample_count = 1,
        };
        /* TEMPORARY F3 diagnostics */
        if (P.diag_nocull) {
            md.cull_mode = SG_CULLMODE_NONE;
        }
        if (P.diag_nodepth) {
            md.depth.compare = SG_COMPAREFUNC_ALWAYS;
            md.depth.write_enabled = false;
        }
        P.mesh_pip[i] = sg_make_pipeline(&md);
    }

    /* D3D11/Metal use a 0..1 depth range: fold the GL-style (-1..1)
       projection into clip space at playback (design D3/D4) */
    P.depth_remap = sg_query_features().origin_top_left ? 1 : 0;

    P.smp = sg_make_sampler(&(sg_sampler_desc){.min_filter = SG_FILTER_LINEAR,
                                               .mag_filter = SG_FILTER_LINEAR});
    P.vbuf = sg_make_buffer(&(sg_buffer_desc){
        .size = 256 * 1024,
        .usage = {.vertex_buffer = true, .dynamic_update = true},
    });
    P.installed = 1;

    static const efx_render_sink sink = {
        NULL, pipe_create_texture, pipe_destroy_texture,
        pipe_create_mesh, pipe_destroy_mesh, NULL, NULL,
    };
    efx_render_install_sink(&sink);
    efx_render_white_texture(); /* engine-owned 1x1 white (design D5) */
}

/* 3D camera + mesh playback (F3): per record, compose MVP from the
 * recorded camera and draw every surface in surface order (design
 * D3/D4/D7); equal-depth fragments resolve by record order because the
 * playback order is the record order */
static void play_mesh_record(const efx_mesh_record *mr, float aspect) {
    pipe_mesh *m = (pipe_mesh *)efx_render_mesh_native(mr->mesh);
    if (!m) {
        return;
    }
    float up[3] = {0, 1, 0};
    float view[16], proj[16], pv[16], mvp[16];
    efx_math_look_at(view, mr->camera.pos, mr->camera.target, up);
    efx_math_perspective(proj, mr->camera.fov, aspect,
                         mr->camera.near_z, mr->camera.far_z);
    efx_math_mul(pv, proj, view);
    efx_math_mul(mvp, pv, mr->transform);
    if (DIAG_CONSTZ) {
        /* every fragment at a constant mid depth: isolates clipping from
           depth-compare behavior */
        mvp[2] = 0.0f;
        mvp[6] = 0.0f;
        mvp[10] = 0.0f;
        mvp[14] = 0.5f * mvp[15];
    } else if (P.depth_remap && !P.diag_noremap) {
        /* row 2 of the clip matrix: z' = 0.5*z_clip + 0.5*w_clip maps the
           GL-style (-1..1) range onto the D3D11/Metal (0..1) range;
           monotonic, so depth comparisons and ties are unchanged */
        mvp[2] *= 0.5f;
        mvp[6] *= 0.5f;
        mvp[10] *= 0.5f;
        mvp[14] = mvp[14] * 0.5f + mvp[15] * 0.5f;
    }

    vs_params_t vs;
    /* the shader computes clip = vec4(dot(mvp0,p), ...) so each vec4 is a
       ROW of the clip matrix: rows[r] = {m[r], m[4+r], m[8+r], m[12+r]} */
    for (int row = 0; row < 4; row++) {
        float *dst = (row == 0) ? vs.mvp0 : (row == 1) ? vs.mvp1
                   : (row == 2) ? vs.mvp2 : vs.mvp3;
        for (int c = 0; c < 4; c++) {
            dst[c] = mvp[c * 4 + row];
        }
    }
    vs.tint[0] = mr->color[0];
    vs.tint[1] = mr->color[1];
    vs.tint[2] = mr->color[2];
    vs.tint[3] = mr->color[3];

    sg_apply_pipeline(P.mesh_pip[mr->blend]);
    for (int i = 0; i < m->surface_count; i++) {
        pipe_mesh_surface *s = &m->surfaces[i];
        if (!s->index_count) {
            continue;
        }
        sg_bindings bnd = {0};
        bnd.vertex_buffers[0] = s->vbuf;
        if (DIAG_NOIB) {
            /* TEMPORARY: bypass the index buffer entirely */
            sg_apply_bindings(&bnd);
            sg_apply_uniforms(UB_vs_params,
                              &(sg_range){.ptr = &vs, .size = sizeof(vs)});
            sg_draw(0, s->vertex_count, 1);
            continue;
        }
        bnd.index_buffer = s->ibuf;
        sg_apply_bindings(&bnd);
        /* documented order: pipeline -> bindings -> uniforms -> draw; the
           single uniform block is per record, applied per surface draw */
        sg_apply_uniforms(UB_vs_params,
                          &(sg_range){.ptr = &vs, .size = sizeof(vs)});
        sg_draw(0, s->index_count, 1);
    }
}

void efx_pipeline_play(void) {
    if (!P.installed) {
        return;
    }
    if (DIAG_HARDCUBE) {
        /* TEMPORARY: hardcoded geometry straight through the pipelines —
           bypasses records, JS, MeshData, pending uploads.
           EFX_DIAG_PROBE=1: quad pipeline + strip (known-good baseline)
           EFX_DIAG_PROBE=2: quad pipeline + TRIANGLES + u32 index buffer
           EFX_DIAG_PROBE=3: mesh pipeline + TRIANGLES + u32 index buffer */
        int probe = 1;
        const char *pv = getenv("EFX_DIAG_PROBE");
        if (pv && *pv) {
            probe = *pv - '0';
        }
        fprintf(stderr, "DIAG: probe %d drawing\n", probe);
        fflush(stderr);
        /* probe 1: FULL-SCREEN quad — unmistakable if it renders.
           stride 20: float2 pos, float2 uv, ub4n rgba */
        static const uint8_t qv[4 * 20] = {
            0, 0, 0, 0xbf, 0, 0, 0, 0xbf, 0, 0, 0, 0, 255, 0, 0, 255,
            0, 0, 0, 0x3f, 0, 0, 0, 0xbf, 0, 0, 0x80, 0x3f, 255, 0, 0, 255,
            0, 0, 0, 0xbf, 0, 0, 0, 0x3f, 0, 0, 0x80, 0x3f, 255, 0, 0, 255,
            0, 0, 0, 0x3f, 0, 0, 0, 0x3f, 0, 0, 0x80, 0x3f, 255, 0, 0, 255,
        };
        static const float tri[7 * 3] = {
            -0.5f, -0.5f, 0.0f, 1, 0, 0, 1,
             0.5f, -0.5f, 0.0f, 0, 1, 0, 1,
             0.0f,  0.5f, 0.0f, 0, 0, 1, 1,
        };
        static sg_buffer qb, qib, tb, tib;
        static int bufs_init;
        if (!bufs_init) {
            qb = sg_make_buffer(&(sg_buffer_desc){
                .data = {.ptr = qv, .size = sizeof(qv)}});
            static const uint32_t qidx[3] = {0, 1, 2};
            qib = sg_make_buffer(&(sg_buffer_desc){
                .usage = {.index_buffer = true}, .data = SG_RANGE(qidx)});
            tb = sg_make_buffer(&(sg_buffer_desc){.data = SG_RANGE(tri)});
            static const uint32_t tidx[3] = {0, 1, 2};
            tib = sg_make_buffer(&(sg_buffer_desc){
                .usage = {.index_buffer = true}, .data = SG_RANGE(tidx)});
            bufs_init = 1;
        }
        if (probe <= 2) {
            /* quad pipeline + quad-format strip/triangles */
            sg_apply_pipeline(P.quad_pip[0]);
            sg_bindings bnd = {0};
            bnd.vertex_buffers[0] = qb;
            if (probe == 2) {
                bnd.index_buffer = qib;
                sg_apply_bindings(&bnd);
                sg_draw(0, 3, 1);
            } else {
                sg_apply_bindings(&bnd);
                sg_draw(0, 4, 1);
            }
        } else {
            vs_params_t vs;
            memcpy(vs.mvp0, (const float[4]){1, 0, 0, 0}, 16);
            memcpy(vs.mvp1, (const float[4]){0, 1, 0, 0}, 16);
            memcpy(vs.mvp2, (const float[4]){0, 0, 1, 0}, 16);
            memcpy(vs.mvp3, (const float[4]){0, 0, 0, 1}, 16);
            vs.tint[0] = 1;
            vs.tint[1] = 1;
            vs.tint[2] = 1;
            vs.tint[3] = 1;
            sg_apply_pipeline(P.mesh_pip[0]);
            sg_bindings bnd = {0};
            bnd.vertex_buffers[0] = tb;
            bnd.index_buffer = tib;
            sg_apply_bindings(&bnd);
            sg_apply_uniforms(UB_vs_params,
                              &(sg_range){.ptr = &vs, .size = sizeof(vs)});
            sg_draw(0, 3, 1);
        }
        return;
    }
    int count = 0;
    const efx_record *records = efx_render_records(&count);
    if (count <= 0) {
        return;
    }
    int run_count = 0;
    const efx_draw_run *runs = efx_render_runs(&run_count);
    if (run_count > 0 && !runs) {
        return;
    }

    int vw = 0, vh = 0;
    efx_render_viewport(&vw, &vh);
    float aspect = (vw > 0 && vh > 0) ? (float)vw / (float)vh : 4.0f / 3.0f;

    /* quad scratch sizing: only the quad records are emitted */
    int quad_count = 0;
    for (int i = 0; i < count; i++) {
        if (records[i].type == EFX_RECORD_QUAD) {
            quad_count++;
        }
    }
    if (quad_count > 0) {
        int cap = quad_count * 6 + 4;
        if (cap > P.scratch_cap) {
            pipe_vertex *grown = realloc(P.scratch, (size_t)cap * sizeof(pipe_vertex));
            if (!grown) {
                return;
            }
            P.scratch = grown;
            P.scratch_cap = cap;
        }
    }

    /* F2 playback: emit ALL quad runs into one dynamic-buffer update
       (multiple updates per frame are unreliable on Metal/D3D11), then
       interleave run draws and mesh records in record order */
    pipe_vertex *v = P.scratch;
    int *run_first = malloc((size_t)(run_count > 0 ? run_count : 1) * sizeof(int));
    int *run_verts = malloc((size_t)(run_count > 0 ? run_count : 1) * sizeof(int));
    if (!run_first || !run_verts) {
        free(run_first);
        free(run_verts);
        return;
    }
    for (int ri = 0; ri < run_count; ri++) {
        run_first[ri] = (int)(v - P.scratch);
        int start = (int)(v - P.scratch);
        for (int q = 0; q < runs[ri].count; q++) {
            if (q > 0) {
                v = emit_quad_bridged(v, &records[runs[ri].start + q].u.quad);
            } else {
                v = emit_quad(v, &records[runs[ri].start + q].u.quad);
            }
        }
        run_verts[ri] = (int)(v - P.scratch) - start;
    }
    int vcount = (int)(v - P.scratch);
    if (vcount > 0) {
        sg_update_buffer(P.vbuf, &(sg_range){.ptr = P.scratch,
                                             .size = (size_t)vcount * sizeof(pipe_vertex)});
    }

    int run_i = 0;
    for (int i = 0; i < count; i++) {
        if (records[i].type == EFX_RECORD_QUAD) {
            if (run_i < run_count && runs[run_i].start == i) {
                sg_apply_pipeline(P.quad_pip[runs[run_i].blend]);
                sg_bindings bnd = {0};
                bnd.vertex_buffers[0] = P.vbuf;
                pipe_tex *t = (pipe_tex *)efx_render_texture_native(runs[run_i].texture);
                if (t) {
                    bnd.views[0] = t->view;
                    bnd.samplers[0] = P.smp;
                    sg_apply_bindings(&bnd);
                    sg_draw(run_first[run_i], run_verts[run_i], 1);
                }
                run_i++;
                i += runs[run_i - 1].count - 1;
            }
        } else {
            play_mesh_record(&records[i].u.mesh, aspect);
        }
    }
    free(run_first);
    free(run_verts);
}

void efx_pipeline_shutdown(void) {
    if (!P.installed) {
        return;
    }
    for (int i = 0; i < 3; i++) {
        sg_destroy_pipeline(P.quad_pip[i]);
        sg_destroy_pipeline(P.mesh_pip[i]);
    }
    sg_destroy_sampler(P.smp);
    sg_destroy_buffer(P.vbuf);
    sg_destroy_shader(P.quad_shd);
    sg_destroy_shader(P.mesh_shd);
    free(P.scratch);
    P.scratch = NULL;
    P.scratch_cap = 0;
    P.installed = 0;
}
